In [1]:
using Plots

In [2]:
include("window.jl")

window (generic function with 1 method)

In [4]:
N = 256

256

In [13]:
type = "boxcar"  # Replace with the desired window type
# N = 10  # Replace with the desired window length
w = window(type, N); # Gives an array of 1.0s

In [14]:
zeros(1, N)

1×256 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [16]:
signal = randn(N); # White Gaussian noise

In [17]:
signal = reshape(signal, 1, :)

1×256 Matrix{Float64}:
 -0.706754  0.291514  -0.496308  -0.568103  …  -0.517343  0.346604  1.36115

In [18]:
vcat(signal, zeros(1, N)) 

2×256 Matrix{Float64}:
 -0.706754  0.291514  -0.496308  -0.568103  …  -0.517343  0.346604  1.36115
  0.0       0.0        0.0        0.0           0.0       0.0       0.0