The covariance matrix is given by the matrix inversion lemma (also known as the Woodbury matrix identity). 

The expression is:

$ C_{\theta | Y} = (C_{\theta\theta}^{-1} + H^T C_{VV}^{-1} H)^{-1} $

The covariance matrix in a Bayesian linear regression context.

In [1]:
using FFTW

In [69]:
include("operations.jl");

In [74]:
using LinearAlgebra
using Distributions: cov, vec

# Simulated data
Y = [1.0, 2.0, 3.0]
H = [1.0; 2.0; 3.0]

# Prior covariance matrix (assuming it's a diagonal matrix for simplicity)
c₀₀ = Diagonal([1.0])

# Likelihood (assuming Gaussian errors)
cᵥᵥ = 0.1 * I

UniformScaling{Float64}
0.1*I

In [91]:
# Bayesian update to calculate posterior covariance
c₀ₗᵥ = ((c₀₀)⁻¹ .+ (H)ᵀ *  (cᵥᵥ)⁻¹ .* H)⁻¹

3×3 Matrix{Float64}:
  1.59192e14  -3.18384e14   1.59192e14
 -3.18384e14   6.36769e14  -3.18384e14
  1.59192e14  -3.18384e14   1.59192e14

In [92]:
using Plots

# Plotting the covariance matrix as a heatmap
plot1 = heatmap(c₀ₗᵥ, xlabel="Variables", ylabel="Variables", title="Covariance Matrix", c=:viridis)
savefig(plot1,"images/plot1.png");

<img src="images/plot1.png" width='' height='' > </img>

### Covariance Numerical Example

In [119]:
Supertech = [-.2 .1 .3 .5] 
Slowpoke = [.05 .2 -.12 .09] # space separator means Row Vector

1×4 Matrix{Float64}:
 0.05  0.2  -0.12  0.09

In [120]:
vec(Slowpoke) # use vec to convert to Column Vector

4-element Vector{Float64}:
  0.05
  0.2
 -0.12
  0.09

In [121]:
# Excel is using the "uncorrected" covariance
answer = -0.004875 # Scalar

-0.004875

In [122]:
answer == cov(vec(Supertech), vec(Slowpoke))

false

In [123]:
answer == cov(vec(Supertech), vec(Slowpoke), corrected=false)

true

In [124]:
H' == transpose.(H) 

false

In [125]:
H == transpose.(H) # Transpose element-wise doesn't do a thing bug ??

true

In [126]:
transpose(H) == permutedims(H) == H'

true

### Toeplitz Matrix Example

In [165]:
using Plots

In [166]:
# Function to generate a Toeplitz matrix
function toeplitz_matrix(c)
    n = length(c)
    T = zeros(n, n)
    for i in 1:n
        for j in 1:n
            T[i, j] = c[abs(i - j) + 1]
        end
    end
    return T
end;

In [168]:
# Example: Toeplitz matrix with first column [1, 2, 3, 4]
c = [1, 2, 3, 4]
T₀ = toeplitz_matrix(c)

4×4 Matrix{Float64}:
 1.0  2.0  3.0  4.0
 2.0  1.0  2.0  3.0
 3.0  2.0  1.0  2.0
 4.0  3.0  2.0  1.0

In [169]:
# Plot the Toeplitz matrix using heatmap
plot2 = 
heatmap(T₀, xlabel="Column Index", ylabel="Row Index", title="Toeplitz Matrix", c=:viridis)
savefig(plot2, "images/plot2.png");

<img src="images/plot2.png" width="" height="" > </img>

In [170]:
using ToeplitzMatrices

In [171]:
# Create a Toeplitz matrix using the toeplitz function
T = Toeplitz(1:length(c),c)

4×4 Toeplitz{Int64, UnitRange{Int64}, Vector{Int64}}:
 1  2  3  4
 2  1  2  3
 3  2  1  2
 4  3  2  1

In [172]:
# Plot the Toeplitz matrix using heatmap
plot3 = heatmap(T, xlabel="Column Index", ylabel="Row Index", title="Toeplitz Matrix", c=:viridis)
savefig(plot3, "images/plot3.png");

<img src="images/plot2.png" width="" height="" > </img>

# References
- [ ] [How to create simple covariance in Julia on a matrix](https://stackoverflow.com/questions/41879024/how-to-create-simple-covariance-in-julia-on-a-matrix)
- [ ] [Bessel's correction](https://en.wikipedia.org/wiki/Bessel%27s_correction)
> Bessel's correction is the use of n − 1 instead of n in the formula for the sample variance and sample standard deviation,